### ISSUE TITLE
Inconsistent polling time units

### ISSUE THREAD

**Issue by FinalFrag** [StefCoene/velserver#7]
Here it mentions 60.000 is 10 minutes, which is incorrect. 60.000 would be 1 minute if we are talking about milliseconds. https://github.com/StefCoene/velserver/blob/2161d5699dc13217146069a7c62b287f6e987cf3/lib/Velbus.pm#L62

In the default config file it says 3.600 = 1 hour, but as far as I can see this would also be in milliseconds, making the correct value 3.600.000.
https://github.com/StefCoene/velserver/blob/8e7e45c44ea6e131d731a1aa0efa66029300457a/etc/openHAB.cfg#L15

**Comment by StefCoene** [comment]
Thank you for reporting.

I fixed it in the config file and in the code.
POLLING is in milliseconds and the default is 60000 = 60 seconds = 1 minute

Stef
